# Generated by Django 4.2.2 on 2023-08-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kategori.kategori')),
            ],
            options={
                'db_table': 'resep',
            },
        ),
    ]
