# Generated by Django 4.2.2 on 2023-08-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kategori.kategori'),
        ),
    ]
